In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
# uncomment this to read and process all excel files again

tennis_df = pd.DataFrame()
for year in range(2001, 2022):
    
    file = ""
    if year < 2013:
        file = f"{year}.xls"
        print(file)
    else:
        assert(year >= 2013)
        file = f"{year}.xlsx"
        print(file)
    
    year_df = pd.read_excel(file)
    year_df['Year'] = year
    tennis_df = tennis_df.append(year_df)

2001.xls
2002.xls
2003.xls
2004.xls
2005.xls
2006.xls
2007.xls
2008.xls
2009.xls
2010.xls
2011.xls
2012.xls
2013.xlsx

C:\Users\briel\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

2014.xlsx
2015.xlsx
2016.xlsx
2017.xlsx
2018.xlsx
2019.xlsx
2020.xlsx
2021.xlsx

In [3]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,Loser,WRank,LRank,W1,L1,W2,L2,W3,L3,W4,L4,W5,L5,Wsets,Lsets,Comment,CBW,CBL,GBW,GBL,IWW,IWL,SBW,SBL,Year,B365W,B365L,B&WW,B&WL,EXW,EXL,PSW,PSL,WPts,LPts,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Clement A.,Gaudenzi A.,18.0,101,6.0,7.0,6.0,0.0,6.0,3.0,NaN,NaN,NaN,NaN,2.0,1.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Goldstein P.,Jones A.,81.0,442,6.0,4.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Haas T.,Smith L.,23.0,485,6.0,3.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,1.12,4.0,1.1,3.5,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Henman T.,Rusedski G.,10.0,69,6.0,2.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Hewitt L.,Arthurs W.,7.0,83,6.0,4.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,1.28,3.3,1.12,3.8,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# file_name = "tennis_data_2001_2021_raw.xlsx"
# tennis_df.to_excel(file_name)

In [5]:
# tennis_df = pd.read_excel(file_name)

In [6]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,Loser,WRank,LRank,W1,L1,W2,L2,W3,L3,W4,L4,W5,L5,Wsets,Lsets,Comment,CBW,CBL,GBW,GBL,IWW,IWL,SBW,SBL,Year,B365W,B365L,B&WW,B&WL,EXW,EXL,PSW,PSL,WPts,LPts,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Clement A.,Gaudenzi A.,18.0,101,6.0,7.0,6.0,0.0,6.0,3.0,NaN,NaN,NaN,NaN,2.0,1.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Goldstein P.,Jones A.,81.0,442,6.0,4.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Haas T.,Smith L.,23.0,485,6.0,3.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,1.12,4.0,1.1,3.5,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Henman T.,Rusedski G.,10.0,69,6.0,2.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3,Hewitt L.,Arthurs W.,7.0,83,6.0,4.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,Completed,1.28,3.3,1.12,3.8,NaN,NaN,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# as of right now, don't see these columns as adding much to the model/data
# once we can get this to work with BET365 then we can look at other books
cols_list_drop = ['Best of', 'W1', 'L1',
       'W2', 'L2', 'W3', 'L3', 'W4', 'L4', 'W5', 'L5', 'Wsets', 'Lsets',
       'Comment', 'CBW', 'CBL', 'GBW', 'GBL', 'IWW', 'IWL', 'SBW', 'SBL',
        'B&WW', 'B&WL', 'EXW', 'EXL', 'PSW', 'PSL',
       'WPts', 'LPts', 'UBW', 'UBL', 'LBW', 'LBL', 'SJW', 'SJL', 'MaxW',
       'MaxL', 'AvgW', 'AvgL']

In [8]:
tennis_df = tennis_df.drop(cols_list_drop, axis=1)

In [9]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L
0,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,Clement A.,Gaudenzi A.,18.0,101,2001,NaN,NaN
1,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,Goldstein P.,Jones A.,81.0,442,2001,NaN,NaN
2,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,Haas T.,Smith L.,23.0,485,2001,NaN,NaN
3,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,Henman T.,Rusedski G.,10.0,69,2001,NaN,NaN
4,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,Hewitt L.,Arthurs W.,7.0,83,2001,NaN,NaN

In [10]:
tennis_df.columns

Index(['ATP', 'Location', 'Tournament', 'Date', 'Series', 'Court', 'Surface',
       'Round', 'Winner', 'Loser', 'WRank', 'LRank', 'Year', 'B365W', 'B365L'],
      dtype='object')

In [11]:
len(tennis_df)

55604

In [12]:
# for year, frame in tennis_df.groupby('Year'):
#     percent_missing = frame.isnull().sum() * 100 / len(frame)
#     missing_value_df = pd.DataFrame({'column_name': frame.columns,
#                                  'percent_missing': percent_missing})
#     print(year)
#     display(missing_value_df)

In [13]:
# dropping all na's because the only NA's were in B365 and in rank - can't run model without either of these
tennis_df = tennis_df.dropna()

In [15]:
# make sure that the drop na worked
percent_missing = tennis_df.isnull().sum() * 100 / len(tennis_df)
missing_value_df = pd.DataFrame({'column_name': tennis_df.columns,
                             'percent_missing': percent_missing})
display(missing_value_df)

           column_name  percent_missing
ATP                ATP              0.0
Location      Location              0.0
Tournament  Tournament              0.0
Date              Date              0.0
Series          Series              0.0
Court            Court              0.0
Surface        Surface              0.0
Round            Round              0.0
Winner          Winner              0.0
Loser            Loser              0.0
WRank            WRank              0.0
LRank            LRank              0.0
Year              Year              0.0
B365W            B365W              0.0
B365L            B365L              0.0

In [16]:
len(tennis_df)

49775

In [17]:
tennis_df.reset_index(inplace=True, drop=True)

In [18]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L
0,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Johansson T.,Pretzsch A.,7.0,133,2002,1.100,6.500
1,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Kafelnikov Y.,Bjorkman J.,6.0,56,2002,1.444,2.625
2,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Koubek S.,Moya C.,41.0,20,2002,2.625,1.444
3,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Pavel A.,Stepanek R.,21.0,150,2002,1.533,2.375
4,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Sampras P.,Stoliarov A.,13.0,107,2002,1.143,5.000

In [19]:
# convert ranks to ints
tennis_df['WRank'] = tennis_df['WRank'].astype(int)
tennis_df['LRank'] = tennis_df['LRank'].astype(int)

In [20]:
tennis_df.dtypes

ATP                    int64
Location              object
Tournament            object
Date          datetime64[ns]
Series                object
Court                 object
Surface               object
Round                 object
Winner                object
Loser                 object
WRank                  int32
LRank                  int32
Year                   int64
B365W                float64
B365L                float64
dtype: object

In [21]:
# can do more eda with this, already see that the rank of of winners is much more than losers
# and that the betting odds for winners are much better than for losers

In [22]:
tennis_df.describe()

,ATP,WRank,LRank,Year,B365W,B365L
count,49775.000000,49775.000000,49775.000000,49775.000000,49775.000000,49775.000000
mean,32.899186,57.585234,89.045384,2011.441085,1.830607,3.493742
std,17.999209,70.496389,110.395155,5.490757,1.119415,3.397872
min,1.000000,1.000000,1.000000,2002.000000,0.971000,0.967000
25%,19.000000,16.000000,34.000000,2007.000000,1.250000,1.720000
50%,33.000000,41.000000,64.000000,2011.000000,1.500000,2.500000
75%,49.000000,76.000000,103.000000,2016.000000,2.100000,3.750000
max,67.000000,1890.000000,2159.000000,2021.000000,34.000000,67.000000

In [23]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L
0,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Johansson T.,Pretzsch A.,7,133,2002,1.100,6.500
1,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Kafelnikov Y.,Bjorkman J.,6,56,2002,1.444,2.625
2,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Koubek S.,Moya C.,41,20,2002,2.625,1.444
3,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Pavel A.,Stepanek R.,21,150,2002,1.533,2.375
4,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Sampras P.,Stoliarov A.,13,107,2002,1.143,5.000

In [24]:
# need to figure out way to standardize round type, this is valuable info that we can't use right now

In [25]:
display(tennis_df['Round'].unique())

array(['1st Round', '2nd Round', '3rd Round', '4th Round',
       'Quarterfinals', 'Semifinals', 'The Final', 'Round Robin'],
      dtype=object)

In [26]:
# convert European odds into probabilities

tennis_df['B365W_prob'] = (1/tennis_df['B365W']).round(3)
tennis_df['B365L_prob'] = (1/tennis_df['B365L']).round(3)

In [27]:
tennis_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
0,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Johansson T.,Pretzsch A.,7,133,2002,1.100,6.500,0.909,0.154
1,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Kafelnikov Y.,Bjorkman J.,6,56,2002,1.444,2.625,0.693,0.381
2,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Koubek S.,Moya C.,41,20,2002,2.625,1.444,0.381,0.693
3,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Pavel A.,Stepanek R.,21,150,2002,1.533,2.375,0.652,0.421
4,32,Halle,Gerry Weber Open,2002-06-10,International,Outdoor,Grass,1st Round,Sampras P.,Stoliarov A.,13,107,2002,1.143,5.000,0.875,0.200

In [28]:
# isolate higher rank
# isolate loser rank
# locate player in df before time series
# find out percentage in win vs loser column
# find surface and other features

In [29]:
tennis_df_historical = tennis_df.copy()

In [33]:
# set up return DF with our new formatted data
final_columns = ['ATP', 'Location', 'Tournament', 'Date', 
                 'Series', 'Court', 'Surface', 'Round',
                'HR_name', 'HR_rank', 'HR_prob', 
                 'LR_name', 'LR_rank', 'LR_prob']
final_df = pd.DataFrame(columns = final_columns)


# iterate through rows of df, for each row we need to do manipulation
for index, row in tennis_df[5000:5005].iterrows():
    
#     create dictionary to return the new row
    returned_row = {}
    returned_row['ATP'] = row['ATP']
    returned_row['Location'] = row['Location']
    returned_row['Tournament'] = row['Tournament']
    returned_row['Date'] = row['Date']
    returned_row['Year'] = row['Year']
    returned_row['Series'] = row['Series']
    returned_row['Court'] = row['Court']
    returned_row['Surface'] = row['Surface']
    returned_row['Round'] = row['Round']
    
    
#     display original df row
    display(row.to_frame().T)
    
#     get date of the match
    date_of_match = row['Date']
    
#     set up information about the winner and loser
    winner = {}
    winner['name'] = row['Winner']
    winner['rank'] = row['WRank']
    winner['prob'] = row['B365W_prob']
    
    loser = {}
    loser['name'] = row['Loser']
    loser['rank'] = row['LRank']
    loser['prob'] = row['B365L_prob']
    
#     figure out the higher and lower rank
    higher_rank = {}
    lower_rank = {}
    if winner['rank'] < loser['rank']:
        higher_rank = winner
        lower_rank = loser
    else:
        higher_rank = loser
        lower_rank = winner
        
#     add name and rank info to returned df
    returned_row['HR_name'] = higher_rank['name']
    returned_row['HR_rank'] = higher_rank['rank']
    returned_row['HR_prob'] = higher_rank['prob']
    returned_row['LR_name'] = lower_rank['name']
    returned_row['LR_rank'] = lower_rank['rank']
    returned_row['LR_prob'] = lower_rank['prob']
    

# isolate the data before the match played where the higher rank player played (wins and losses)
    higher_rank_name = higher_rank['name']
    print(higher_rank_name)
    print(date_of_match)
    higher_rank_history = tennis_df_historical.loc[(tennis_df_historical['Winner'] == higher_rank_name) | (tennis_df_historical['Loser'] == higher_rank_name)]
    higher_rank_history = higher_rank_history[higher_rank_history['Date'] < date_of_match]
    
#     isolate last 10 games for player
    higher_rank_last_10 = higher_rank_history[-10:]
    
    display(higher_rank_last_10)
    
    final_df = final_df.append(returned_row, ignore_index = True)

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
5000,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Robredo T.,Massu N.,17,11,2004,1.667,2.1,0.6,0.476

Massu N.
2004-05-28 00:00:00

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
4616,23,Monte Carlo,Monte Carlo Masters,2004-04-20,Masters,Outdoor,Clay,1st Round,Massu N.,Saretta F.,11,52,2004,1.571,2.250,0.637,0.444
4635,23,Monte Carlo,Monte Carlo Masters,2004-04-21,Masters,Outdoor,Clay,2nd Round,Massu N.,Lopez F.,11,24,2004,1.615,2.200,0.619,0.455
4651,23,Monte Carlo,Monte Carlo Masters,2004-04-22,Masters,Outdoor,Clay,3rd Round,Henman T.,Massu N.,7,11,2004,1.833,1.833,0.546,0.546
4694,24,Barcelona,Open Seat Godo,2004-04-28,International Gold,Outdoor,Clay,2nd Round,Martin A.,Massu N.,56,11,2004,1.727,2.000,0.579,0.500
4749,26,Rome,Telecom Italia Masters Roma,2004-05-04,Masters,Outdoor,Clay,1st Round,Massu N.,Dell'Acqua M.,11,182,2004,1.222,4.000,0.818,0.250
4767,26,Rome,Telecom Italia Masters Roma,2004-05-05,Masters,Outdoor,Clay,2nd Round,Massu N.,Labadze I.,11,51,2004,1.667,2.100,0.600,0.476
4781,26,Rome,Telecom Italia Masters Roma,2004-05-06,Masters,Outdoor,Clay,3rd Round,Massu N.,Safin M.,11,25,2004,3.500,1.286,0.286,0.778
4789,26,Rome,Telecom Italia Masters Roma,2004-05-07,Masters,Outdoor,Clay,Quarterfinals,Zabaleta M.,Massu N.,40,11,2004,1.800,1.909,0.556,0.524
4814,27,Hamburg,Hamburg TMS,2004-05-11,Masters,Outdoor,Clay,1st Round,Melzer J.,Massu N.,68,11,2004,3.500,1.286,0.286,0.778
4975,30,Paris,French Open,2004-05-26,Grand Slam,Outdoor,Clay,2nd Round,Massu N.,Voltchkov V.,11,171,2004,1.167,4.500,0.857,0.222

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
5001,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Coria G.,Ancic M.,3,73,2004,1.063,8.0,0.941,0.125

Coria G.
2004-05-28 00:00:00

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
4658,23,Monte Carlo,Monte Carlo Masters,2004-04-24,Masters,Outdoor,Clay,Semifinals,Coria G.,Safin M.,4,25,2004,1.444,2.625,0.693,0.381
4660,23,Monte Carlo,Monte Carlo Masters,2004-04-25,Masters,Outdoor,Clay,The Final,Coria G.,Schuettler R.,4,6,2004,1.286,3.750,0.778,0.267
4809,27,Hamburg,Hamburg TMS,2004-05-10,Masters,Outdoor,Clay,1st Round,Coria G.,Almagro N.,3,133,2004,1.071,7.500,0.934,0.133
4826,27,Hamburg,Hamburg TMS,2004-05-12,Masters,Outdoor,Clay,2nd Round,Coria G.,Horna L.,3,45,2004,1.125,5.500,0.889,0.182
4849,27,Hamburg,Hamburg TMS,2004-05-13,Masters,Outdoor,Clay,3rd Round,Coria G.,Robredo T.,3,19,2004,1.250,3.750,0.800,0.267
4852,27,Hamburg,Hamburg TMS,2004-05-14,Masters,Outdoor,Clay,Quarterfinals,Coria G.,Ferrer D.,3,57,2004,1.125,5.500,0.889,0.182
4855,27,Hamburg,Hamburg TMS,2004-05-15,Masters,Outdoor,Clay,Semifinals,Coria G.,Ljubicic I.,3,40,2004,1.111,6.000,0.900,0.167
4856,27,Hamburg,Hamburg TMS,2004-05-16,Masters,Outdoor,Clay,The Final,Federer R.,Coria G.,1,3,2004,1.444,2.625,0.693,0.381
4910,30,Paris,French Open,2004-05-24,Grand Slam,Outdoor,Clay,1st Round,Coria G.,Davydenko N.,3,57,2004,1.125,5.500,0.889,0.182
4964,30,Paris,French Open,2004-05-26,Grand Slam,Outdoor,Clay,2nd Round,Coria G.,Monaco J.,3,143,2004,1.040,9.000,0.962,0.111

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
5002,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Moya C.,Sluiter R.,5,82,2004,1.05,9.0,0.952,0.111

Moya C.
2004-05-28 00:00:00

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
4786,26,Rome,Telecom Italia Masters Roma,2004-05-07,Masters,Outdoor,Clay,3rd Round,Moya C.,Karlovic I.,9,70,2004,1.167,4.500,0.857,0.222
4790,26,Rome,Telecom Italia Masters Roma,2004-05-07,Masters,Outdoor,Clay,Quarterfinals,Moya C.,Pavel A.,9,30,2004,1.444,2.625,0.693,0.381
4792,26,Rome,Telecom Italia Masters Roma,2004-05-08,Masters,Outdoor,Clay,Semifinals,Moya C.,Zabaleta M.,9,40,2004,1.400,2.750,0.714,0.364
4793,26,Rome,Telecom Italia Masters Roma,2004-05-09,Masters,Outdoor,Clay,The Final,Moya C.,Nalbandian D.,9,8,2004,1.570,2.370,0.637,0.422
4825,27,Hamburg,Hamburg TMS,2004-05-11,Masters,Outdoor,Clay,1st Round,Moya C.,Sanchez D.,8,51,2004,1.222,4.000,0.818,0.250
4838,27,Hamburg,Hamburg TMS,2004-05-12,Masters,Outdoor,Clay,2nd Round,Moya C.,Martin A.,8,59,2004,1.222,4.000,0.818,0.250
4848,27,Hamburg,Hamburg TMS,2004-05-13,Masters,Outdoor,Clay,3rd Round,Moya C.,Verdasco F.,8,52,2004,1.364,3.000,0.733,0.333
4850,27,Hamburg,Hamburg TMS,2004-05-14,Masters,Outdoor,Clay,Quarterfinals,Federer R.,Moya C.,1,8,2004,1.400,2.750,0.714,0.364
4905,30,Paris,French Open,2004-05-24,Grand Slam,Outdoor,Clay,1st Round,Moya C.,van Lottum J.,5,98,2004,1.040,9.000,0.962,0.111
4969,30,Paris,French Open,2004-05-26,Grand Slam,Outdoor,Clay,2nd Round,Moya C.,Vicente F.,5,148,2004,1.040,9.000,0.962,0.111

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
5003,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Mutis O.,Santoro F.,125,58,2004,2.0,1.727,0.5,0.579

Santoro F.
2004-05-28 00:00:00

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
4233,14,Marseille,Open 13,2004-02-24,International,Indoor,Hard,1st Round,Sargsian S.,Santoro F.,42,71,2004,1.800,1.909,0.556,0.524
4297,16,Dubai,Dubai Championships,2004-03-02,International Gold,Outdoor,Hard,1st Round,Santoro F.,Martin A.,73,55,2004,2.000,1.727,0.500,0.579
4302,16,Dubai,Dubai Championships,2004-03-03,International Gold,Outdoor,Hard,2nd Round,Schalken S.,Santoro F.,15,73,2004,1.333,3.250,0.750,0.308
4364,18,Indian Wells,Pacific Life Open,2004-03-13,Masters,Outdoor,Hard,1st Round,Sanguinetti D.,Santoro F.,112,72,2004,2.250,1.571,0.444,0.637
4452,19,Miami,NASDAQ-100 Open,2004-03-25,Masters,Outdoor,Hard,1st Round,Hernych J.,Santoro F.,160,79,2004,1.900,1.800,0.526,0.556
4603,23,Monte Carlo,Monte Carlo Masters,2004-04-19,Masters,Outdoor,Clay,1st Round,Santoro F.,Andreev I.,76,80,2004,2.500,1.500,0.400,0.667
4630,23,Monte Carlo,Monte Carlo Masters,2004-04-21,Masters,Outdoor,Clay,2nd Round,Santoro F.,Dent T.,76,34,2004,1.833,1.833,0.546,0.546
4650,23,Monte Carlo,Monte Carlo Masters,2004-04-22,Masters,Outdoor,Clay,3rd Round,Nalbandian D.,Santoro F.,9,76,2004,1.222,4.000,0.818,0.250
4946,30,Paris,French Open,2004-05-25,Grand Slam,Outdoor,Clay,1st Round,Santoro F.,Clement A.,58,33,2004,2.200,1.615,0.455,0.619
4976,30,Paris,French Open,2004-05-26,Grand Slam,Outdoor,Clay,2nd Round,Santoro F.,Labadze I.,58,50,2004,2.200,1.615,0.455,0.619

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
5004,30,Paris,French Open,2004-05-29,Grand Slam,Outdoor,Clay,3rd Round,Gaudio G.,Enqvist T.,44,65,2004,1.2,4.333,0.833,0.231

Gaudio G.
2004-05-29 00:00:00

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Winner,Loser,WRank,LRank,Year,B365W,B365L,B365W_prob,B365L_prob
4634,23,Monte Carlo,Monte Carlo Masters,2004-04-21,Masters,Outdoor,Clay,2nd Round,Hewitt L.,Gaudio G.,19,35,2004,1.667,2.100,0.600,0.476
4668,24,Barcelona,Open Seat Godo,2004-04-26,International Gold,Outdoor,Clay,1st Round,Gaudio G.,Sluiter R.,39,78,2004,1.200,4.000,0.833,0.250
4695,24,Barcelona,Open Seat Godo,2004-04-28,International Gold,Outdoor,Clay,2nd Round,Gaudio G.,Popp A.,39,84,2004,1.125,5.500,0.889,0.182
4696,24,Barcelona,Open Seat Godo,2004-04-29,International Gold,Outdoor,Clay,3rd Round,Gaudio G.,Moya C.,39,9,2004,2.750,1.400,0.364,0.714
4706,24,Barcelona,Open Seat Godo,2004-04-30,International Gold,Outdoor,Clay,Quarterfinals,Gaudio G.,Kuerten G.,39,23,2004,1.800,1.909,0.556,0.524
4708,24,Barcelona,Open Seat Godo,2004-05-01,International Gold,Outdoor,Clay,Semifinals,Gaudio G.,Montanes A.,39,82,2004,1.500,2.500,0.667,0.400
4710,24,Barcelona,Open Seat Godo,2004-05-02,International Gold,Outdoor,Clay,The Final,Robredo T.,Gaudio G.,26,39,2004,2.000,1.727,0.500,0.579
4822,27,Hamburg,Hamburg TMS,2004-05-11,Masters,Outdoor,Clay,1st Round,Federer R.,Gaudio G.,1,34,2004,1.333,3.250,0.750,0.308
4963,30,Paris,French Open,2004-05-26,Grand Slam,Outdoor,Clay,1st Round,Gaudio G.,Canas G.,44,72,2004,1.571,2.250,0.637,0.444
4991,30,Paris,French Open,2004-05-27,Grand Slam,Outdoor,Clay,2nd Round,Gaudio G.,Novak J.,44,14,2004,1.500,2.500,0.667,0.400

In [34]:
display(final_df)

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,HR_name,HR_rank,HR_prob,LR_name,LR_rank,LR_prob,Year
0,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Massu N.,11,0.476,Robredo T.,17,0.600,2004.0
1,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Coria G.,3,0.941,Ancic M.,73,0.125,2004.0
2,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Moya C.,5,0.952,Sluiter R.,82,0.111,2004.0
3,30,Paris,French Open,2004-05-28,Grand Slam,Outdoor,Clay,3rd Round,Santoro F.,58,0.579,Mutis O.,125,0.500,2004.0
4,30,Paris,French Open,2004-05-29,Grand Slam,Outdoor,Clay,3rd Round,Gaudio G.,44,0.833,Enqvist T.,65,0.231,2004.0

In [35]:
# can either just focus on higher rank, and get info about his past and ooppondent's past
# or can take the difference in odds, which require us breaking each player into 2 rows, creating a regression on each, then subtracting the odds difference

# think the higher rank version is better option, focuses on just 1 regression and 1 decision

In [36]:
# tennis_df.to_excel("tennis_data_2001_2021.xlsx")